server:
  port: 8762
spring:
  profiles:
    active: development
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - name: Path
              args:
                pattern: "/orders/**"
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - name: Path
              args:
                pattern: "/payments/**"
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - name: Path
              args:
                pattern: "/stocks/**"
logging:
  level:
    root: INFO
    kafka.*: WARN
    org.springframework.*: INFO
    org.neo4j.*: INFO
    com.memorynotfound: DEBUG
    org.apache.kafka.*: ERROR
---
spring:
  profiles: development
  cloud:
    kubernetes.discovery.enabled: false
    kubernetes.ribbon.enabled: false
    kubernetes.enabled: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: test
eureka:
  client:
    enabled: false